// Generated by https://quicktype.io

export interface PerPbr {
  종목코드: string;
  종목명: string;
  종가: number;
  대비: number;
  등락률: number;
  EPS: number | null;
  PER: number | null;
  선행EPS: number | null;
  선행PER: number | null;
  BPS: number | null;
  PBR: number | null;
  주당배당금: number;
  배당수익률: number;
}
